### ISSUE TITLE
Add more free dev resources

### ISSUE THREAD

**Issue by dlcastillop** [yossTheDev/devplace#1]
Free dev resources:

Name: Nova.js
Link: https://novajs.co
Description: A collection of dependency-free React hooks

---

Name: Hook Crafter
Link: https://github.com/dlcastillop/hook-crafter
Description: a template to build a React hook library faster

**Comment by dlcastillop** [comment]
I would added myself, but apparently the resources are located on a database.

**Comment by yossdotpro** [comment]
> I would added myself, but apparently the resources are located on a database. 

Thanks Daniel. The resources are in the repository inside the Resources folder sorted by categories. We will improve the documentation to make this process clearer 😁.

**Comment by yossdotpro** [comment]
Your requested resources are now in the Directory 🚀
